/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opencv_template_convert_ImageConverter */

#ifndef _Included_org_opencv_template_convert_ImageConverter
#define _Included_org_opencv_template_convert_ImageConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opencv_template_convert_ImageConverter
 * Method:    nativeDetect
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_opencv_template_convert_ImageConverter_nativeConvert
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
